LibDS: MulticastDNS Class Reference
MulticastDNS Class Reference
Public Slots
void lookup (const QString &name)
Signals
void finished (const QHostInfo &info)
Private Slots
void onReadyRead ()
Private Member Functions
QString getHost (const QByteArray &data)
QString getIPv4 (const QByteArray &data, const QString &host)
QString getIPv6 (const QByteArray &data, const QString &host, const QString &ipv4)
QList< QHostAddress > getAddresses (const QByteArray &data, const QString &host)
Private Attributes
bool m_IPv4Binded
bool m_IPv6Binded
QUdpSocket m_IPv4Socket
QUdpSocket m_IPv6Socket
Member Function Documentation
QList< QHostAddress > MulticastDNS::getAddresses (const QByteArray & data, const QString & host) private
Obtains the IPv4 and IPv6 addresses from the received data.
Note
This function will only generate a list with the valid IP addresses.
References getIPv4(), and getIPv6().
Referenced by onReadyRead().
QString MulticastDNS::getHost (const QByteArray & data) private
Extracts the host name from the data received from the mDNS network. The host name begins at byte #12 (when the header and flags end) and ends with a mandatory NUL character after the domain.
The host name is constructed in the following way (without spaces): NAME_LENGTH + NAME + DOMAIN_LENGTH + DOMAIN + NUL
For example, appletv.local would be formatted as: 0x07 + appletv + 0x05 + local + 0x00
Or, if you prefer hex data: { 07 61 70 70 6c 65 74 76 05 6c 6f 63 61 6c 00 } { 7 a p p l e t v 5 l o c a l 0 }
In order to obtain the full host name (and its mDNS domain), we construct the string backwards. When the code notices that the current character is the same as the domain length, we know that the domain name has been extracted, and thus we can replace the domain length with a dot (.) and begin extracting the host name.
Referenced by onReadyRead().
QString MulticastDNS::getIPv4 (const QByteArray & data, const QString & host) private
Extracts the IPv4 from the data received from the mDNS network. The IPv4 data begins when the host name data ends. We can know if the IPv4 information is present in the packet by looking at the type codes, which are the first two bytes after the host name data.
For the packet to contain IPv4 information, the type codes must be 0x00 and 0x01 respectively. After the type codes, we have two bytes that represent the IP class codes, the following four bytes contain the TTL (which we do not use FYI). After the TTL, we have a byte that represents the number of bytes that construct the IPv4 address. After that, we finally have the address bytes (which we can extract if we know the IPv4 length, which is usually 4).
Here is the 'layout' of the IPv4 section of the packet:
Type codes: {0x00 0x01} (used for verification)
Class Codes: {0x80 0x01} (used for verification)
TTL (four bytes)
IP length (one byte)
IP address bytes (depend on length)
This is an example IPv4 section: {00 01 80 01 00 00 78 00 00 04 99 6d 07 5a}
Data in example section:
{00 01} Type Codes
{80 01} Class Codes
{00 00 78 00 00} IP TTL
{04} Number of address bytes (length in layman's terms)
{99 6d 07 5a} IPv4 Address bytes (153, 109, 7, 90)
Referenced by getAddresses().
QString MulticastDNS::getIPv6 (const QByteArray & data, const QString & host, const QString & ipv4) private
Extracts the IPv6 from the data received from the mDNS network. The IPv6 data begins when the IPv4 data and the two-byte FQDN ends. As with the IPv4 code, we can know if the IPv6 information is present in the packet by looking at the type codes, which are the first two bytes after the IPv4 and FQDN data.
For the packet to contain IPv6 information, the type codes must be 0x00 and 0x1C respectively. After the type codes, we have two bytes that represent the IP class codes, the following four bytes contain the TTL (which we do not use FYI). After the TTL, we have a byte that represents the number of bytes that construct the IPv6 address. After that, we finally have the address bytes (which we can extract if we know the IPv6 length, which is usually 16).
Here is the 'layout' of the IPv4 section of the packet:
Type codes: {0x00 0xC1} (used for verification)
Class Codes: {0x80 0x01} (used for verification)
TTL (four bytes)
IP length (one byte)
IP address bytes (depend on length, usually 16)
This is an example IPv6 section: { 00 1c 80 01 00 00 78 00 00 10 fe 80 00 } { 00 00 00 00 00 02 23 32 ff fe b1 21 52 }
Data in example section:
{00 1c} Type Codes
{80 01} Class Codes
{00 00 78 00 00} IP TTL
{10} Number of address bytes (length in layman's terms)
{fe 80 00 00 ... 52} IPv6 Address bytes (there are 16 of them)
Referenced by getAddresses().
void MulticastDNS::lookup (const QString & name) slot
Performs a mDNS lookup to find the IP address of the given host name.
Note
If the alreadySupported() function returns true, then this class will use the native implementation of the OS to find the given host name.
If the alreadySupported() function returns false, then this class will perform the mDNS lookup by itself using Qt socket programming.
Referenced by Lookup::lookup().
void MulticastDNS::onReadyRead () private slot
Called when we receive data from a mDNS service on the network.
Note
We will only take into account mDNS response packets, not queries.
References getAddresses(), and getHost().
The documentation for this class was generated from the following files:
MulticastDNS.h
MulticastDNS.cpp